### ISSUE TITLE
路由扁平化后，又想用嵌套路由的公共布局怎么办呢？

### ISSUE THREAD

**Issue by sir-ran** [jsxiaosi/min-xs-admin#1]
路由扁平化后，又想用嵌套路由的公共布局怎么办呢？

**Comment by jsxiaosi** [comment]
扁平化路由是为了解决keepAlive三级路由渲染两次问题，你可以参考以下方案：

1. 去除扁平化路由
    扁平化路由后需要自己手动修改initAsyncRoute方法里面的privilegeRouting更新路由列表逻辑，目前这里的方法是通过扁平化路由去做权限过滤，然后再按照一下举例方案去解决keepAlive重复渲染问题：
   - 把三级路由全部开启keepAlive（还会触发渲染一次）
   - 关闭keepAlive

4. 通过组件的形式套在三级路由页面
